#编写配置 key: value
#app.name
app:
  name: Lession07-yml
  owner: fan01
  port: 9000

# 导入其他的配置
spring:
  config:
    import: conf/db.yml,conf/redis.yml
  #激活某个配置文件(环境)
  profiles:
    active: dev
    #group 优先active
    group:
      "dev": test

myapp:
  name: Lession07-yml
  owner: fan01
  port: 9000
  security:
    username: lisi
    password: 24213

#第三方对象
security:
  username: root123
  password: 4332432


#配置集合
#数组和List一样,使用"-" 一个成员
names:
  - zhangsan
  - lisi
#List<MyServer> servers
servers:
  - title: 华南服务器
    ip: 202.23.3.4
  - title: 西北服务器
    ip: 32.423.4.2
# Map<String,User> users
users:
  user1:
    name: 张三
    sex: 男
    age: 22
  user2:
    name: 李四
    sex: 女
    age: 28
