#指定初始的book数据,代替数据库
product:
  books:
    - isbn: 8001
      name: java
      author: lisi
    - isbn: 8002
      name: tomcat
      author: zhangsan
    - isbn: 8003
      name: jvm
      author: zousdd

# 访问路径
server:
  servlet:
    context-path: /api
#开启支持RFC7807
spring:
  mvc:
    problemdetails:
      enabled: true
