@startuml
'https://plantuml.com/class-diagram

abstract class AbstractClass{
+ template(): void
+ operation2(): void
+ operation3(): void
+ operation4(): void
}
class ConcreateClass{
+ operation2(): void
+ operation3(): void
+ operation4(): void
}
class ConcreateClassB

ConcreateClass --|> AbstractClass
ConcreateClassB --|> AbstractClass

Client ..> ConcreateClassB
Client ..> ConcreateClass
@enduml