@startuml
'https://plantuml.com/class-diagram

interface Map{
+ put(): void
+ putAll(): void
}
abstract class AbstractHashMap

class HashMap

class Node

AbstractHashMap ..|> Map
HashMap --|> AbstractHashMap

HashMap o-- Node

Client ..>HashMap

@enduml