@startuml
'https://plantuml.com/class-diagram

interface Component{
+opration()
+add(Component)
+remove(Component)
+getChild(Int)
}
class Leaf{
+opration()
}
class Composite{
+add(Component)
+remove(Component)
+getChild(Int)
+opration()
}

Component <|.. Leaf
Component <|.. Composite
Composite o-- Component

Client ..> Component

@enduml